### ISSUE TITLE
about README

### ISSUE THREAD

**Issue by RockyLim92** [miumida/naver_weather#2]
리드미에서 "HA설정에 naver_weather weather를 추가합니다" 라는 문구가 정확히 어떤 의미인지 알려주실 수 있나요??

아래와 같이 yaml 파일에 추가하는것 외에 더 추가해주어야할 것이 있나요??

```
weather:
  - platform: naver_weather
    area: '날씨'
    sensor_use: 'Y'
```

감사합니다.
